version = 0.1

[default.deploy.parameters]
stack_name = "chaplin-poop-manager-v1"
resolve_s3 = true
s3_prefix = "chaplin-poop-manager-v1"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "ChaplinApiKey=\"CPCPADOIRLSA38\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
